Repository Seagate/cortx-prvsnr, pull requests merged in 2021-06, with the labels that each got.

#1316 Improvement - Network configuration and prepare
  lr-cli/cortx_setup/commands/network/config.py
  lr-cli/cortx_setup/commands/node/prepare/network.py
Labels: cla-signed

#1315 EOS-20665: Field Prepare - Storage configuration
  lr-cli/cortx_setup/api_spec.yaml
  lr-cli/cortx_setup/commands/__init__.py
  lr-cli/cortx_setup/commands/node/prepare/storage.py
  lr-cli/cortx_setup/commands/storage/commons.py
  lr-cli/cortx_setup/commands/storage/config.py
Labels: cla-signed

#1305 EOS-20679 : Get ISO version
  api/python/provisioner/__init__.py
  api/python/provisioner/api.py
  api/python/provisioner/api_spec.yaml
  api/python/provisioner/commands/upgrade/__init__.py
  api/python/provisioner/commands/upgrade/get_iso_version.py
Labels: cla-signed

#1318 EOS-20676: [upgrade pre-validation] Ensure that an active upgrade ISO is available
  api/python/provisioner/commands/check.py
  api/python/provisioner/commands/upgrade/sw_upgrade.py
  api/python/provisioner/config.py
Labels: cla-signed

#1321 [Tests] Field: Storageset test case scenarios
  test/r2.md
Labels: cla-signed

#1322 EOS-20788 sw upgrade follow up fixes
  .dockerignore
  api/python/provisioner/cli_spec.yaml
  api/python/provisioner/commands/__init__.py
  api/python/provisioner/commands/mini_api/mini_api.py
  api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
  api/python/provisioner/commands/upgrade/sw_upgrade.py
  api/python/provisioner/commands/upgrade/sw_upgrade_node.py
  api/python/provisioner/cortx_ha.py
  api/python/provisioner/errors.py
  api/python/provisioner/inputs.py
  api/python/provisioner/srv/salt/repos/init.sls
  api/python/provisioner/srv/salt/repos/upgrade.sls
  api/python/provisioner/srv/salt/resources/3rd_party/saltstack/salt-master/config.sls
  api/python/provisioner/srv/salt/resources/3rd_party/saltstack/salt-minion/config.sls
  api/python/provisioner/utils.py
  api/python/requirements/codacy.txt
  api/python/requirements/install.txt
  api/python/requirements/tests.txt
  api/python/setup.py
  images/docker/Dockerfile.setup.tmpl
  srv/components/misc_pkgs/mocks/cortx/build_upgrade.sls
  srv/components/misc_pkgs/mocks/cortx/files/scripts/buildrpm.sh
  srv/components/misc_pkgs/mocks/cortx/prepare.sls
  test/api/python/integration/swupgrade/test_swupgrade.py
  test/api/python/provisioner/test_utils.py
  test/testapi/integration.py
Labels: cla-signed

#1326 EOS-20788: Fix version for prerequistite requests package
  api/python/requirements/install.txt
Labels: cla-signed

#1327 EOS-20862:refresh pillar to update enclosure id
  api/python/provisioner/commands/setup_provisioner.py
Labels: cla-signed

#1332 EOS-20580: Remove consul check for HA
  api/python/provisioner/commands/deploy.py
  api/python/provisioner/commands/deploy_dual.py
  api/python/provisioner/commands/deploy_vm.py
Labels: cla-signed

#1324 added test cases for field prepare - time configuration
  test/r2.md
Labels: cla-signed

#1335 EOS-21068: Open port 80 on Management and Public Data ports
  pillar/components/firewall.sls
Labels: cla-signed

#1329 EOS-20788 sw upgrade follow up fixes (#1322)
  .dockerignore
  api/python/provisioner/cli_spec.yaml
  api/python/provisioner/commands/__init__.py
  api/python/provisioner/commands/mini_api/mini_api.py
  api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
  api/python/provisioner/commands/upgrade/sw_upgrade.py
  api/python/provisioner/commands/upgrade/sw_upgrade_node.py
  api/python/provisioner/cortx_ha.py
  api/python/provisioner/errors.py
  api/python/provisioner/inputs.py
  api/python/provisioner/srv/salt/repos/init.sls
  api/python/provisioner/srv/salt/repos/upgrade.sls
  api/python/provisioner/srv/salt/resources/3rd_party/saltstack/salt-master/config.sls
  api/python/provisioner/srv/salt/resources/3rd_party/saltstack/salt-minion/config.sls
  api/python/provisioner/utils.py
  api/python/requirements/codacy.txt
  api/python/requirements/install.txt
  api/python/requirements/tests.txt
  api/python/setup.py
  images/docker/Dockerfile.setup.tmpl
  srv/components/misc_pkgs/mocks/cortx/build_upgrade.sls
  srv/components/misc_pkgs/mocks/cortx/files/scripts/buildrpm.sh
  srv/components/misc_pkgs/mocks/cortx/prepare.sls
  test/api/python/integration/swupgrade/test_swupgrade.py
  test/api/python/provisioner/test_utils.py
  test/conftest.py
  test/testapi/integration.py
Labels: cla-signed

#1320 [TestCases] Added test scenario for cluster defination
  test/r2.md
Labels: cla-signed

#1319 Update test scenarios for network factory and field commands
  lr-cli/cortx_setup/commands/common_utils.py
  lr-cli/cortx_setup/commands/node/prepare/network.py
  test/r2.md
Labels: cla-signed

#1343 EOS-21068: Open port 80 on Management and Public Data ports
  cli/src/virtual_appliance/bootstrap.sh
  pillar/components/firewall.sls
Labels: cla-signed

#1328 EOS-20920: added validation for config.ini interfaces and devices
  api/python/provisioner/commands/configure_setup.py
  api/python/provisioner/commands/validator/config_sections.py
Labels: cla-signed

#1339 [EOS-20908] Collect pillar data from all nodes
  lr-cli/cortx_setup/api_spec.yaml
  lr-cli/cortx_setup/commands/__init__.py
  lr-cli/cortx_setup/commands/cluster/config/network.py
  lr-cli/cortx_setup/commands/cluster/create.py
  lr-cli/cortx_setup/commands/network/config.py
  lr-cli/cortx_setup/commands/node/prepare/config.py
  lr-cli/cortx_setup/commands/node/prepare/network.py
  lr-cli/cortx_setup/commands/node/prepare/server.py
  lr-cli/cortx_setup/commands/node/prepare/storage.py
  lr-cli/cortx_setup/commands/node/prepare/time.py
  lr-cli/cortx_setup/commands/pillar_sync.py
  lr-cli/cortx_setup/commands/storage/config.py
  lr-cli/cortx_setup/commands/storageset/add/enclosure.py
  lr-cli/cortx_setup/commands/storageset/add/node.py
  lr-cli/cortx_setup/commands/storageset/config/durability.py
  lr-cli/cortx_setup/commands/storageset/create.py
  lr-cli/cortx_setup/config.py
  lr-cli/cortx_setup/log.py
Labels: cla-signed

#1340 EOS-20788 sw upgrade follow up fixes (#1322) (#1329)
  .dockerignore
  api/python/provisioner/cli_spec.yaml
  api/python/provisioner/commands/__init__.py
  api/python/provisioner/commands/mini_api/mini_api.py
  api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
  api/python/provisioner/commands/upgrade/sw_upgrade.py
  api/python/provisioner/commands/upgrade/sw_upgrade_node.py
  api/python/provisioner/cortx_ha.py
  api/python/provisioner/errors.py
  api/python/provisioner/inputs.py
  api/python/provisioner/srv/salt/repos/init.sls
  api/python/provisioner/srv/salt/repos/upgrade.sls
  api/python/provisioner/srv/salt/resources/3rd_party/saltstack/salt-master/config.sls
  api/python/provisioner/srv/salt/resources/3rd_party/saltstack/salt-minion/config.sls
  api/python/provisioner/utils.py
  api/python/requirements/codacy.txt
  api/python/requirements/install.txt
  api/python/requirements/tests.txt
  api/python/setup.py
  devops/rpms/api/build_python_api.sh
  images/docker/Dockerfile.setup.tmpl
  srv/components/misc_pkgs/mocks/cortx/build_upgrade.sls
  srv/components/misc_pkgs/mocks/cortx/files/scripts/buildrpm.sh
  srv/components/misc_pkgs/mocks/cortx/prepare.sls
  test/api/python/integration/swupgrade/test_swupgrade.py
  test/api/python/provisioner/test_utils.py
  test/conftest.py
  test/testapi/integration.py
Labels: cla-signed

#1349 [EOS-20908] Taking backup of confstore in glusterfs
  lr-cli/cortx_setup/commands/pillar_sync.py
  srv/components/provisioner/confstore.sls
Labels: cla-signed

#1348 Updated HA deploy states for hardware
  api/python/provisioner/commands/deploy.py
  srv/components/ha/corosync-pacemaker/teardown.sls
Labels: cla-signed

#980 EOS-18493: Create a generic create user api
  api/python/provisioner/api.py
  api/python/provisioner/commands/__init__.py
  api/python/provisioner/commands/create_user.py
Labels: cla-signed

#1301 jenkins-fix: updated config.ini file config
  devops/ci/multi_node_deploy/3node_deploy.jenkinsfile
  devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
  devops/ci/single_node_deploy/deploy.jenkinsfile
  devops/ci/single_node_deploy/deploy_iso.jenkinsfile
  devops/ci/single_node_deploy/destroy.jenkinsfile
Labels: cla-signed

#1352 EOS-21082: Fix issues if machine_id or cluster_id is missing
  lr-cli/cortx_setup/commands/common_utils.py
Labels: cla-signed

#1351 Update testing documentation with unit testing guidelines
  docs/Architecture/Test-Guidelines.md
  docs/Development/testing.md
Labels: cla-signed

#1330 EOS-20788 mini api spec changes
  api/python/provisioner/__metadata__.py
  api/python/provisioner/api_spec.yaml
  api/python/provisioner/cli_parser.py
  api/python/provisioner/cli_spec.yaml
  api/python/provisioner/commands/mini_api/__init__.py
  api/python/provisioner/commands/mini_api/common.py
  api/python/provisioner/commands/mini_api/hook_caller.py
  api/python/provisioner/commands/mini_api/mini_api.py
  api/python/provisioner/commands/mini_api/spec_renderer.py
  api/python/provisioner/commands/upgrade/get_iso_version.py
  api/python/provisioner/commands/upgrade/get_swupgrade_info.py
  api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
  api/python/provisioner/commands/upgrade/sw_upgrade.py
  api/python/provisioner/commands/upgrade/sw_upgrade_node.py
  api/python/provisioner/config.py
  api/python/provisioner/inputs.py
  docs/mini_prvsnr_api.md
  pillar/components/commons.sls
  pillar/components/upgrade.sls
  srv/_modules/prvsnr.py
  srv/_modules/setup_conf.py
  srv/components/misc_pkgs/mocks/cortx/files/scripts/mock.py
  srv/components/misc_pkgs/mocks/cortx/files/setup.yaml
  test/api/python/integration/swupgrade/test_swupgrade.py
  test/testapi/integration.py
Labels: cla-signed

#1353 EOS-21003: Remove port forwarding in firewall
  srv/components/system/firewall/config.sls
Labels: cla-signed

#1338 EOS-21033, EOS-21058: Fail if any destroy stage fails
  api/python/provisioner/commands/destroy.py
  srv/components/csm/teardown/cleanup.sls
  srv/components/csm/teardown/reset.sls
  srv/components/ha/cortx-ha/ha_cleanup.sls
  srv/components/ha/cortx-ha/teardown/cleanup.sls
  srv/components/ha/cortx-ha/teardown/init.sls
  srv/components/ha/cortx-ha/teardown/reset.sls
  srv/components/hare/teardown/cleanup.sls
  srv/components/hare/teardown/reset.sls
  srv/components/motr/teardown/cleanup.sls
  srv/components/motr/teardown/reset.sls
  srv/components/s3server/teardown/cleanup.sls
  srv/components/s3server/teardown/reset.sls
  srv/components/sspl/teardown/cleanup.sls
  srv/components/sspl/teardown/reset.sls
Labels: cla-signed

#1331 EOS-20918: Create granular command for mini-provisioner config
  api/python/provisioner/commands/deploy.py
  lr-cli/cortx_setup/api_spec.yaml
  lr-cli/cortx_setup/commands/__init__.py
  lr-cli/cortx_setup/commands/common_utils.py
  lr-cli/cortx_setup/commands/node/prepare/cortx.py
  pillar/components/execution.sls
  srv/components/cortx_utils/config/init.sls
Labels: cla-signed

#1317 EOS-20863: Ensure response from Zookeeper before starting Kafka
  srv/components/misc_pkgs/kafka/files/zookeeper.properties
  srv/components/misc_pkgs/kafka/start.sls
  srv/components/misc_pkgs/kafka/stop.sls
Labels: cla-signed

#1334 EOS-21003: Adjust mtu value for static IP config on VM
  cli/src/virtual_appliance/bootstrap.sh
  srv/components/system/firewall/config.sls
  srv/components/system/network/data/direct/init.sls
  srv/components/system/network/data/public/init.sls
Labels: R1, bug, cla-signed

#1355 [EOS-21124] Added validation of host and ipv4
  lr-cli/cortx_setup/commands/cluster/config/network.py
  lr-cli/cortx_setup/commands/node/prepare/config.py
  lr-cli/cortx_setup/commands/node/prepare/network.py
  lr-cli/cortx_setup/commands/node/prepare/time.py
  lr-cli/cortx_setup/validate.py
Labels: cla-signed

#1357 [EOS-20906] makes cortx-ha wrappers initialization lazy
  api/python/provisioner/commands/__init__.py
  api/python/provisioner/cortx_ha.py
  api/python/provisioner/scm/saltstack/rc_sls/base.py
  api/python/provisioner/values.py
Labels: cla-signed

#1346 EOS-21101: lr-cli fetch enclosure_id from controller with plain password
  lr-cli/cortx_setup/commands/storage/config.py
  lr-cli/cortx_setup/commands/storage/enclosure_info.py
Labels: cla-signed

#1345 EOS-19569: Clarifying salt-master related strings
  cli/src/factory_ops/unboxing/init
  cli/src/factory_ops/unboxing/pre_unbox
  docs/User-Guides/Deploy VM ISO Repo.md
  pillar/components/storage.sls
  srv/components/provisioner/salt_master/files/master
  srv/components/provisioner/salt_minion/files/minion
  srv/components/provisioner/salt_minion/files/minion_factory
  test/srv/components/system/config/test_setup_ssh_sls.py
Labels: cla-signed

#1360 EOS-20788: fixes support for legacy mini api logic
  api/python/provisioner/__metadata__.py
  api/python/provisioner/commands/mini_api/spec_renderer.py
  api/python/provisioner/config.py
  api/python/provisioner/cortx_ha.py
  srv/_modules/setup_conf.py
  test/api/python/integration/swupgrade/test_swupgrade.py
Labels: cla-signed

#1363 EOS-20788: follow up fix - adds missed cortx-utils
  pillar/components/commons.sls
  pillar/components/upgrade.sls
Labels: cla-signed

#1267 EOS-20415: Setup 3 node K8s cluster
  srv/k8s/containerd/config.sls
  srv/k8s/containerd/init.sls
  srv/k8s/containerd/install.sls
  srv/k8s/containerd/prepare.sls
  srv/k8s/containerd/start.sls
  srv/k8s/containerd/stop.sls
  srv/k8s/containerd/teardown.sls
  srv/k8s/docker/config.sls
  srv/k8s/docker/init.sls
  srv/k8s/docker/install.sls
  srv/k8s/docker/prepare.sls
  srv/k8s/docker/sanity_check.sls
  srv/k8s/docker/start.sls
  srv/k8s/docker/stop.sls
  srv/k8s/docker/teardown.sls
  srv/k8s/init.sls
  srv/k8s/kube/config/calico.sls
  srv/k8s/kube/config/finalize.sls
  srv/k8s/kube/config/init.sls
  srv/k8s/kube/config/kubeadm.sls
  srv/k8s/kube/init.sls
  srv/k8s/kube/install.sls
  srv/k8s/kube/prepare/init.sls
  srv/k8s/kube/prepare/kube_repo.sls
  srv/k8s/kube/prepare/nw_bridge.sls
  srv/k8s/kube/prepare/setup_selinux.sls
  srv/k8s/kube/sanity_check.sls
  srv/k8s/kube/start.sls
  srv/k8s/kube/stop.sls
  srv/k8s/kube/teardown.sls
  srv/k8s/prepare.sls
  srv/k8s/teardown.sls
Labels: cla-signed

#1362 patch for time config failure in the absence of enclosure_id
  lr-cli/cortx_setup/commands/node/prepare/time.py
Labels: cla-signed

#1354 EOS-21163: Remove cluster_id during node prepare server phase
  lr-cli/cortx_setup/api_spec.yaml
  lr-cli/cortx_setup/commands/__init__.py
  lr-cli/cortx_setup/commands/cluster/config/component.py
  lr-cli/cortx_setup/commands/common_utils.py
  lr-cli/cortx_setup/commands/node/prepare/config.py
  lr-cli/cortx_setup/commands/node/prepare/server.py
  lr-cli/cortx_setup/commands/node/prepare/software.py
  pillar/components/execution.sls
Labels: cla-signed

#1361 EOS-21181: cortx_setup command fails to set enclosure_id
  lr-cli/cortx_setup/commands/storage/commons.py
Labels: cla-signed

#1366 EOS-20788: allows multiple sw on top level of mini spec
  api/python/provisioner/commands/mini_api/spec_renderer.py
  pillar/components/commons.sls
Labels: cla-signed

#1368 Documentation for K8s use
  srv/k8s/README.md
Labels: cla-signed

#1359 EOS-21182: Remove rabbitmq from deployment and teardown
  api/python/provisioner/commands/deploy.py
  api/python/provisioner/commands/destroy.py
  cli/src/virtual_appliance/bootstrap.sh
  srv/components/misc_pkgs/rabbitmq/teardown.sls
Labels: cla-signed

#1364 Remove installation of cortx-py-utils dependencies
  srv/components/system/config/pillar_encrypt.sls
  srv/components/system/files/cortx_py_utils_requirements.txt
Labels: cla-signed

#1216 EOS-19470: Elasticsearch and Kibana deployment using Opendistro
  pillar/components/commons.sls
  srv/components/misc_pkgs/elasticsearch/config.sls
  srv/components/misc_pkgs/elasticsearch/files/elasticsearch.yml.j2
  srv/components/misc_pkgs/elasticsearch/init.sls
  srv/components/misc_pkgs/elasticsearch/install.sls
  srv/components/misc_pkgs/elasticsearch/teardown.sls
  srv/components/misc_pkgs/kibana/config.sls
  srv/components/misc_pkgs/kibana/files/kibana.yml.j2
  srv/components/misc_pkgs/kibana/init.sls
  srv/components/misc_pkgs/kibana/install.sls
  srv/components/misc_pkgs/kibana/teardown.sls
  srv/components/system/files/cortx_py_utils_requirements.txt
Labels: awaiting_confidence_vote, cla-signed

#1373 EOS-20677: Ensure that no active upgrade ISO is available
  api/python/provisioner/commands/check.py
  api/python/provisioner/commands/upgrade/get_iso_version.py
  api/python/provisioner/commands/upgrade/get_swupgrade_info.py
  api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
  api/python/provisioner/config.py
  test/api/python/provisioner/test_sw_upgrade.py
Labels: cla-signed

#1374 EOS-20678: Ensure that upgrade is not running
  api/python/provisioner/commands/upgrade/remove_swupgrade_repo.py
Labels: cla-signed

#1342 EOS-20669: Update provisioner to use new ISO structure in scope of upgrade
  api/python/provisioner/commands/upgrade/get_swupgrade_info.py
  api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
  api/python/provisioner/commands/validator/validator.py
  api/python/provisioner/config.py
  api/python/provisioner/inputs.py
  api/python/provisioner/utils.py
Labels: cla-signed

#1372 [EOS-20783][EOS-20784] adds usage for new HA interfaces
  api/python/provisioner/__metadata__.py
  api/python/provisioner/commands/upgrade/sw_upgrade.py
  api/python/provisioner/config.py
  api/python/provisioner/cortx_ha.py
Labels: cla-signed

#1379 fixed bug in cortx-jenkins job command
  devops/jenkins/cortx_jenkins/jobs.py
Labels: cla-signed

#1378 Fix for jenkins deploy job failure
  devops/ci/single_node_deploy/deploy.jenkinsfile
Labels: cla-signed

#1383 EOS-21185: Increase replication factor for 3-node kafka cluster
  srv/components/misc_pkgs/kafka/config.sls
Labels: cla-signed

#1387 EOS-20783: follow up, marks 'cortx status' as not available
  api/python/provisioner/cortx_ha.py
Labels: cla-signed

#1384 EOS-21344, EOS-19911: Configure firewall settings
  pillar/components/execution.sls
  pillar/components/firewall.sls
  pillar/components/glusterfs.sls
  srv/components/system/firewall/config.sls
  srv/components/system/firewall/teardown.sls
Labels: cla-signed

#1382 EOS-21227: Improvements - Factory and Field process
  lr-cli/cortx_setup/api_spec.yaml
  lr-cli/cortx_setup/commands/__init__.py
  lr-cli/cortx_setup/commands/node/initialize.py
  lr-cli/cortx_setup/commands/node/prepare/network.py
  pillar/components/execution.sls
Labels: cla-signed

#1389 certificate installation command
  lr-cli/cortx_setup/commands/security/config.py
  lr-cli/cortx_setup/config.py
  lr-cli/cortx_setup/validate.py
Labels: cla-signed

#1390 EOS-19965: [SW_UPGRADE][HOT_FIX]: GPG signature validation fix & other minor fixes
  api/python/provisioner/__metadata__.py
  api/python/provisioner/commands/upgrade/check_iso_authenticity.py
  api/python/provisioner/commands/upgrade/get_swupgrade_info.py
  api/python/provisioner/commands/validator/validator.py
Labels: cla-signed

#1394 remove processes in teardown
  devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
  devops/ci/single_node_deploy/destroy.jenkinsfile
Labels: cla-signed

#1396 Merge #1394 regression addressed
  devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
  devops/ci/single_node_deploy/destroy.jenkinsfile
Labels: cla-signed

#1385 EOS-21265: NodePrepare improvements to field deployment process.
  lr-cli/cortx_setup/commands/node/prepare/software.py
  srv/components/system/network/mgmt/ip_alias/init.sls
Labels: cla-signed

#1376 EOS-21287, EOS-21227, EOS-21197: lr-cli factory server config and factory storage config for vm
  lr-cli/cortx_setup/api_spec.yaml
  lr-cli/cortx_setup/commands/__init__.py
  lr-cli/cortx_setup/commands/node/prepare/storage.py
  lr-cli/cortx_setup/commands/node/prepare/time.py
  lr-cli/cortx_setup/commands/server/__init__.py
  lr-cli/cortx_setup/commands/server/config.py
  lr-cli/cortx_setup/commands/storage/config.py
  lr-cli/cortx_setup/commands/storage/enclosure_info.py
Labels: cla-signed

#1398 [EOS-21368] removed default values for create cluster command
  lr-cli/cortx_setup/commands/cluster/create.py
Labels: cla-signed

#1377 EOS-21421 : updated config.ini validations for data and matadata devices
  api/python/provisioner/commands/configure_setup.py
  api/python/provisioner/commands/validator/config_sections.py
Labels: cla-signed

#1399 Update test results for sprint-45/46
  test/r2.md
Labels: cla-signed

#1380 EOS-19686: Logic incorporated for unsupported feature
  devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
  devops/ci/single_node_deploy/destroy.jenkinsfile
  srv/_modules/cortx_unsupported_features.py
  srv/components/csm/config/config.sls
  test/r2.md
Labels: cla-signed

#1409 EOS-21916: Factory: Missing Mini-Provisioner ConfStore default keys
  lr-cli/cortx_setup/api_spec.yaml
  lr-cli/cortx_setup/commands/__init__.py
  lr-cli/cortx_setup/commands/confstore.py
  srv/components/system/files/factory_confstore_template.j2
Labels: cla-signed

#1412 EOS-21920 : remove rabbitmq from all deploy files
  api/python/provisioner/commands/deploy.py
  api/python/provisioner/commands/deploy_dual.py
  api/python/provisioner/commands/deploy_jbod.py
  api/python/provisioner/commands/deploy_vm.py
  api/python/provisioner/commands/destroy.py
  api/python/provisioner/config.py
  pillar/components/commons.sls
  srv/components/misc_pkgs/init.sls
Labels: cla-signed

#1411 EOS-21413 : updated cluster-id logic
  api/python/provisioner/commands/cluster_id.py
  api/python/provisioner/commands/setup_provisioner.py
  srv/_grains/cluster-id.py
Labels: cla-signed

#1375 added tests for EOS-19470: ELasticsearch and kibana deployment
  test/r2.md
Labels: cla-signed

#1405 [EOS-21294] Validate devices , interfaces and health , manifest
  lr-cli/cortx_setup/commands/node/finalize.py
  lr-cli/cortx_setup/config.py
  lr-cli/cortx_setup/validate.py
Labels: cla-signed

#1406 [EOS-21925] Added support for BMC in network config
  lr-cli/cortx_setup/commands/common_utils.py
  lr-cli/cortx_setup/commands/network/config.py
  lr-cli/cortx_setup/config.py
Labels: cla-signed

#1400 EOS-21222: Add cvg and devices to the storage config module.
  lr-cli/cortx_setup/commands/storage/config.py
Labels: cla-signed

#1393 EOS-21362: Generate resource map
  lr-cli/cortx_setup/commands/resource/discover.py
  lr-cli/cortx_setup/config.py
Labels: cla-signed

#1407 EOS-21905: lr-cli: node prepare server gives salt-related errors
  lr-cli/cortx_setup/commands/node/prepare/config.py
  lr-cli/cortx_setup/commands/node/prepare/server.py
Labels: cla-signed

#1414 EOS-20030: bootstrap minor changes for robustness
  lr-cli/cortx_setup/commands/cluster/create.py
  lr-cli/cortx_setup/commands/cluster/generate.py
Labels: cla-signed

#1418 Fix: cluster config and prepare commands
  lr-cli/cortx_setup/api_spec.yaml
  lr-cli/cortx_setup/commands/__init__.py
  lr-cli/cortx_setup/commands/cluster/config/component.py
  lr-cli/cortx_setup/commands/cluster/prepare.py
  pillar/components/execution.sls
Labels: cla-signed

#1416 [MGMT_VIP] add support for mgmt_vip in cluster network
  lr-cli/cortx_setup/commands/cluster/config/network.py
Labels: cla-signed

#1423 EOS-21961: addressed minor bootstrap and ntp issues
  api/python/provisioner/commands/bootstrap_provisioner.py
  lr-cli/cortx_setup/commands/cluster/create.py
  lr-cli/cortx_setup/commands/node/prepare/time.py
  lr-cli/cortx_setup/commands/storage/config.py
  srv/components/controller/ntp.sls
Labels: cla-signed

#1413 EOS-20429: SW Upgrade pre validation - upgrade of CORTX components is compatible with the current version
  api/python/provisioner/commands/check.py
  api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
  api/python/provisioner/commands/validator/validator.py
  api/python/provisioner/config.py
  api/python/provisioner/utils.py
  devops/rpms/cortx-prvsnr.spec
Labels: cla-signed

#1428 [MGMT_VIP] fixed management vip and dns server
  lr-cli/cortx_setup/commands/cluster/config/network.py
  lr-cli/cortx_setup/commands/cluster/create.py
Labels: cla-signed

#1431 Changes to cluster prepare and config wrt prerequisite states
  lr-cli/cortx_setup/commands/cluster/config/component.py
  lr-cli/cortx_setup/commands/cluster/prepare.py
Labels: cla-signed

#1433 [NodePrepareFinalize] wrapper of salt cleanup command
  lr-cli/cortx_setup/api_spec.yaml
  lr-cli/cortx_setup/commands/__init__.py
  lr-cli/cortx_setup/commands/node/prepare/finalize.py
Labels: cla-signed

#1432 EOS-21921: addressed integration issues
  api/python/provisioner/commands/bootstrap_provisioner.py
  api/python/provisioner/commands/cluster_id.py
  lr-cli/cortx_setup/commands/cluster/create.py
  lr-cli/cortx_setup/commands/cluster/prepare.py
  lr-cli/cortx_setup/commands/node/prepare/time.py
  lr-cli/cortx_setup/commands/storage/config.py
  pillar/components/execution.sls
  srv/_grains/enclosure.py
Labels: cla-signed

#1430 EOS-19962: Review and activate pre validations for disruptive upgrade of CORTX SW
  api/python/provisioner/commands/check.py
  api/python/provisioner/commands/upgrade/sw_upgrade.py
  api/python/provisioner/config.py
Labels: cla-signed

#1434 EOS-19965: fixes identified misses
  api/python/provisioner/api.py
  api/python/provisioner/commands/upgrade/sw_upgrade.py
  api/python/provisioner/commands/upgrade/sw_upgrade_node.py
  api/python/provisioner/config.py
  api/python/provisioner/cortx_ha.py
  srv/_modules/setup_conf.py
Labels: cla-signed

#1437 Add cortx_prep script
  srv/components/provisioner/salt_minion/files/minion_factory
  srv/components/provisioner/scripts/cortx_prep.sh
Labels: cla-signed

#1436 EOS-21921: addressed integration issues
  srv/components/csm/config/config.sls
  srv/components/system/network/mgmt/public/init.sls
Labels: cla-signed

#1425 Increment cvg_count by 1 with each successful run of 'storage config' command with 'cvg' option.
  lr-cli/cortx_setup/commands/storage/config.py
Labels: cla-signed

#1438 [EOS-20036] run ha component in sequence primary and then secondaries
  lr-cli/cortx_setup/commands/cluster/config/component.py
Labels: cla-signed

#1403 EOS-21363: Generate healthview for specific resource with specific state
  lr-cli/cortx_setup/commands/resource/discover.py
  lr-cli/cortx_setup/commands/resource/show.py
  lr-cli/cortx_setup/config.py
Labels: cla-signed

#1440 [Fix] Sync salt data in pillar
  lr-cli/cortx_setup/commands/node/initialize.py
Labels: cla-signed

#1439 Add missing cortx packages
  srv/components/provisioner/scripts/cortx_prep.sh
Labels: cla-signed

#1441 Cortx Setup storage config - refresh key map only after getting the machine id
  lr-cli/cortx_setup/commands/storage/config.py
Labels: cla-signed

#1429 EOS-19961: Review and activate pre validations for disruptive upgrade of CORTX SW
  api/python/provisioner/__metadata__.py
  api/python/provisioner/api.py
  api/python/provisioner/commands/upgrade/check_iso_authenticity.py
  api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
  test/api/python/provisioner/test_sw_upgrade.py
Labels: cla-signed

#1442 [SW_Upgrade]: Improve communicability check for SW upgrade
  api/python/provisioner/commands/check.py
Labels: cla-signed

#1443 [Fix_transport_mode] Support for transport param in network config
  lr-cli/cortx_setup/commands/network/config.py
Labels: cla-signed
