Repository Seagate/cortx-prvsnr, pull requests merged in 2022-08, with the labels that each got.

#6393 CORTX-33648: lock unlock implementation for migrating config generation to consul
  src/provisioner/const.py
  src/provisioner/provisioner.py
  test/setup/test_provisioner.py
Labels: cla-signed

#6396 revert deployment time PR
  src/provisioner/provisioner.py
Labels: cla-signed

#6397 CORTX-33763: add deployment time in gconf
  src/provisioner/provisioner.py
Labels: cla-signed

#6398 CORTX-33855: remove extra arrow from update provisioning status
  src/provisioner/provisioner.py
Labels: cla-signed

#6395 remove kailashyadaw from codeowners list
  CODEOWNERS
Labels: cla-signed, Status: Waiting to be Merged

#6400 CORTX-33673: update lock unlock parameters with new improvment changes
  src/provisioner/provisioner.py
Labels: cla-signed

#6399 Update Codacy Badge
  README.md
Labels: cla-signed, Status: Waiting to Reviewed

#6401 CORTX-33905: Update CODEOWNERS
  CODEOWNERS
Labels: cla-signed

#6402 CORTX-33499: update rgw gc parameters in gconf sample files
  conf/gconf/cluster.conf.sample
  conf/solution/config.yaml.sample
  test/setup/config.yaml
Labels: cla-signed

#6403 CORTX-32833: resolve codacy issues from provisioner repo
  setup.py
  src/provisioner/provisioner.py
  src/provisioner/validators.py
  test/setup/test_invalid_cluster_config.py
  test/setup/test_invalid_cortx_conf.py
  test/setup/test_multiple_storage_sets.py
  test/setup/test_provisioner.py
Labels: cla-signed

#6404 CORTX-32833: update readme.md file in provisioner/test for running un…
  src/README.md
  test/README.md
Labels: cla-signed
